# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructors',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructors',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='instructors',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=1),
        ),
        migrations.AddField(
            model_name='instructors',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instructors',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='instructors',
            name='slug',
            field=models.SlugField(default='False'),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='course',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='name',
            field=models.CharField(help_text='This is as name', max_length=255, verbose_name='Instructors Name'),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='surname',
            field=models.CharField(max_length=255, verbose_name='Second name'),
        ),
    ]
