# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0003_auto_20171109_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructors',
            name='course',
        ),
        migrations.AddField(
            model_name='instructors',
            name='course',
            field=models.ManyToManyField(null=True, to='instructors.Course'),
        ),
    ]
