# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 10:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructors', '0004_auto_20171109_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructors',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
